# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170917_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to=b'', verbose_name='\u5934\u50cf', width_field=150),
        ),
    ]
